import { RuntimeError } from '@ethlete/core';

// codes 1600-1699
export const STREAM_ERROR_CODES = {
  MISSING_CONSENT_TOKEN: 1600,
  SCRIPT_LOAD_FAILED: 1601,
  TWITCH_SDK_NOT_AVAILABLE: 1602,
  YOUTUBE_SDK_NOT_AVAILABLE: 1603,
  MISSING_PIP_CHROME_TOKEN: 1604,
  FACEBOOK_SDK_NOT_AVAILABLE: 1605,
  VIMEO_SDK_NOT_AVAILABLE: 1606,
  TIKTOK_PLAYER_ERROR: 1607,
  FACEBOOK_VIDEO_UNAVAILABLE: 1608,
  YOUTUBE_PLAYER_ERROR: 1609,
  MISSING_PIP_ENTRY: 1610,
  MISSING_STREAM_SOURCE: 1611,
  MISSING_STREAM_PIP_PROVIDER: 1612,
} as const;

export const missingStreamSourceError = (player: string, inputs: string) =>
  new RuntimeError(
    STREAM_ERROR_CODES.MISSING_STREAM_SOURCE,
    `[${player}] Nothing to play: no source resolved. Set ${inputs}.`,
  );
