import { Tree } from '@nx/devkit';

export const QUERY_CLIENT_FEATURES_REPORT_PATH = 'query-client-features-migration-tasks.md';

export const MIGRATION_TASK_KIND = {
  WARNING: 'warning',
  MANUAL_REVIEW: 'manual-review',
  FOLLOW_UP: 'follow-up',
} as const;

export type MigrationTaskKind = (typeof MIGRATION_TASK_KIND)[keyof typeof MIGRATION_TASK_KIND];

export type MigrationTaskLocation = {
  filePath: string;
  line?: number;
};

export type MigrationTask = {
  id: string;
  kind: MigrationTaskKind;
  title: string;
  summary: string;
  action: string;
  locations: MigrationTaskLocation[];
  source: string;
  dedupeKey: string;
};

type AddMigrationTaskInput = {
  kind: MigrationTaskKind;
  title: string;
  summary: string;
  action: string;
  locations?: MigrationTaskLocation[];
  source: string;
  dedupeKey?: string;
};

const renderTaskLocations = (locations: readonly MigrationTaskLocation[]) => {
  if (locations.length === 0) {
    return '- None recorded';
  }

  return locations.map((location) => `- ${location.filePath}${location.line ? `:${location.line}` : ''}`).join('\n');
};

export class QueryClientFeaturesMigrationReport {
  tasks: MigrationTask[] = [];

  addTask(input: AddMigrationTaskInput) {
    const dedupeKey = input.dedupeKey ?? `${input.kind}:${input.title}:${input.summary}:${input.action}`;
    const existing = this.tasks.find((task) => task.dedupeKey === dedupeKey);

    if (existing) {
      existing.locations.push(...(input.locations ?? []));
      return;
    }

    this.tasks.push({
      id: `QCF-${String(this.tasks.length + 1).padStart(3, '0')}`,
      kind: input.kind,
      title: input.title,
      summary: input.summary,
      action: input.action,
      locations: input.locations ?? [],
      source: input.source,
      dedupeKey,
    });
  }

  addWarning(input: Omit<AddMigrationTaskInput, 'kind'>) {
    this.addTask({ ...input, kind: MIGRATION_TASK_KIND.WARNING });
  }

  addManualReview(input: Omit<AddMigrationTaskInput, 'kind'>) {
    this.addTask({ ...input, kind: MIGRATION_TASK_KIND.MANUAL_REVIEW });
  }

  addFollowUp(input: Omit<AddMigrationTaskInput, 'kind'>) {
    this.addTask({ ...input, kind: MIGRATION_TASK_KIND.FOLLOW_UP });
  }

  printSummary() {
    if (this.tasks.length === 0) {
      return;
    }

    console.warn(`\n⚠️ Generated ${this.tasks.length} follow-up task${this.tasks.length === 1 ? '' : 's'}:`);

    this.tasks.forEach((task) => {
      const locations = task.locations
        .map((location) => `${location.filePath}${location.line ? `:${location.line}` : ''}`)
        .join(', ');

      console.warn(` - ${task.id} [${task.kind}] ${task.title}${locations ? ` (${locations})` : ''}`);
    });

    console.warn(`\n📄 See ${QUERY_CLIENT_FEATURES_REPORT_PATH} for the AI-ready follow-up list.`);
  }

  writeToTree(tree: Tree) {
    tree.write(QUERY_CLIENT_FEATURES_REPORT_PATH, renderMigrationReportMarkdown(this.tasks));
  }
}

export const renderMigrationReportMarkdown = (tasks: readonly MigrationTask[]) => {
  const header = [
    '# Query Client Features Migration Follow-Up',
    '',
    'This file is generated by the `migrate-query-client-features` generator.',
    '',
    '## Context',
    '',
    'Multi-tab sync and query persistence used to be on by default and are now opt-in features of',
    '`createQueryClient`. The codemod is **behavior preserving**: every client that did not opt out',
    'gets `withMultiTabSync()` / `withQueryPersistence()` so it keeps working exactly as before.',
    'That is rarely what an app wants long term — dropping a feature it never relied on removes the',
    'whole subsystem from the bundle, so review each added feature and delete the ones you do not need.',
    '',
    '## AI Instructions',
    '',
    '1. Re-read the referenced files before changing anything. The migration output is only a starting point.',
    '2. Prefer minimal fixes that align with the current runtime APIs in `@ethlete/query`.',
    '3. Update or remove a task only after the code and tests confirm that it is resolved.',
    '4. If a task is still ambiguous after inspection, keep it open and append a short note instead of guessing.',
    '',
    '## Task Format',
    '',
    '- `Status`: always treat generated tasks as `open` until verified manually or by tests.',
    '- `Kind`: `warning`, `manual-review`, or `follow-up`.',
    '- `Source`: which migration phase raised the task.',
    '',
  ].join('\n');

  if (tasks.length === 0) {
    return `${header}## Tasks\n\nNo open follow-up tasks were recorded during this migration run.\n`;
  }

  const tasksSection = tasks
    .map((task) =>
      [
        `### ${task.id} - ${task.title}`,
        '',
        '- Status: open',
        `- Kind: ${task.kind}`,
        `- Source: ${task.source}`,
        `- Summary: ${task.summary}`,
        `- Suggested action: ${task.action}`,
        '- Locations:',
        renderTaskLocations(task.locations),
        '',
      ].join('\n'),
    )
    .join('');

  const machineSection = [
    '## Machine Summary',
    '',
    '```yaml',
    'tasks:',
    ...tasks.flatMap((task) => {
      const nestedLocations = task.locations.flatMap((location) => {
        const lines = [`      - filePath: ${location.filePath}`];

        if (location.line) {
          lines.push(`        line: ${location.line}`);
        }

        return lines;
      });

      return [
        `  - id: ${task.id}`,
        `    status: open`,
        `    kind: ${task.kind}`,
        `    source: ${task.source}`,
        `    title: ${task.title}`,
        `    summary: ${task.summary}`,
        `    action: ${task.action}`,
        `    locations:`,
        ...(nestedLocations.length > 0 ? nestedLocations : ['      []']),
      ];
    }),
    '```',
    '',
  ].join('\n');

  return `${header}## Tasks\n\n${tasksSection}${machineSection}`;
};
