#!/usr/bin/env node
/**
 * Sourcemap-attributed decomposition of an `@ethlete` bundle: "which original source files are
 * these bytes?".
 *
 * measure-bundle.mjs answers "how many bytes"; this answers "whose". The published FESM is one
 * flattened file, so an esbuild metafile has ~4 inputs and tells you nothing. Instead the sourcemap
 * is kept alive through the whole pipeline:
 *
 *   dist FESM + its .map  --babel(link+optimize, sourceMaps, inputSourceMap)-->
 *   linked .mjs + chained .map  --esbuild(minify, sourcemap:external)-->
 *   out.js + out.js.map  -->  attribute every generated byte to its original source
 *
 * Byte attribution: mappings are sorted by generated position and each segment owns the bytes from
 * its column to the next segment (or end of line). Bytes with no mapping are `<unmapped>` (esbuild
 * glue, the entry itself). Attribution is in MINIFIED bytes — gzip cannot be attributed per module,
 * so compare shares, and take the gz total from the header line.
 *
 * Note this uses its own cache dir (`linked-sm-<fingerprint>`), because the FESMs must be re-linked
 * with sourcemaps enabled.
 *
 * Usage:
 *   node tools/treeshake/decompose.mjs --entry "<source code>" [--name paginate]
 *   node tools/treeshake/decompose.mjs --entries <file.json>
 *     [--dist <dist/libs>] [--cache <dir>] [--out <dir>] [--top 25] [--json <file>] [--dump <file>]
 *
 * Example:
 *   node tools/treeshake/decompose.mjs --name floor \
 *     --entry "import { paginate } from '@ethlete/components'; console.log(paginate);" \
 *     --dump floor-unmin.js --json floor.json
 *   # then: node tools/treeshake/retention.mjs <tmp>/ethlete-treeshake/floor-unmin.js
 */
import { gzipSync } from 'node:zlib';
import { join, resolve } from 'node:path';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import {
  OUT_ROOT,
  assertOutsideRepo,
  defaultDistLibs,
  distFingerprint,
  esbuildBase,
  externalizeNonEthlete,
  makeArgs,
  processPackages,
  repoRequire,
} from './harness.mjs';

const esbuild = repoRequire('esbuild');
const { decode } = repoRequire('@jridgewell/sourcemap-codec');
const { arg } = makeArgs();

const distLibs = resolve(arg('dist', defaultDistLibs()));
const outDir = assertOutsideRepo(arg('out', OUT_ROOT), 'decompose output');
const topN = Number(arg('top', 25));
/** resolve a user-supplied output path against the out dir, and never inside the repo */
const outPath = (p) => assertOutsideRepo(resolve(outDir, p), 'decompose output');

/** normalize a sourcemap `sources` entry to a repo-relative path */
const normalize = (s) => {
  if (!s) return '<unmapped>';
  const i = s.indexOf('libs/');
  if (i !== -1) return s.slice(i);
  const j = s.indexOf('node_modules/');
  if (j !== -1) return s.slice(j);
  return s;
};

const decompose = async (name, code, aliases, workDir, { dump } = {}) => {
  const entry = join(workDir, `dec-${name}.mjs`);
  await writeFile(entry, code.endsWith('\n') ? code : `${code}\n`, 'utf8');
  const common = { ...esbuildBase(), entryPoints: [entry], alias: aliases, plugins: [externalizeNonEthlete] };

  const min = await esbuild.build({
    ...common,
    outfile: join(workDir, `${name}.out.js`), // esbuild requires an out path for an external map
    minify: true,
    sourcemap: 'external',
    metafile: true,
  });
  const out = Buffer.from(min.outputFiles.find((f) => f.path.endsWith('.js')).contents);
  const map = JSON.parse(Buffer.from(min.outputFiles.find((f) => f.path.endsWith('.map')).contents).toString('utf8'));
  const gz = gzipSync(out, { level: 9 }).byteLength;

  if (dump) {
    const un = await esbuild.build({ ...common, minify: false });
    await writeFile(dump, Buffer.from(un.outputFiles[0].contents));
  }

  const lines = decode(map.mappings);
  const lineTexts = out.toString('utf8').split('\n');
  const bySource = new Map();
  const add = (k, n) => bySource.set(k, (bySource.get(k) ?? 0) + n);

  for (let li = 0; li < lines.length; li++) {
    const segs = lines[li];
    if (!segs?.length) continue;
    const lineLen = (lineTexts[li]?.length ?? 0) + 1; // + newline
    const sorted = [...segs].sort((a, b) => a[0] - b[0]);
    if (sorted[0][0] > 0) add('<unmapped>', sorted[0][0]);
    for (let i = 0; i < sorted.length; i++) {
      const end = i + 1 < sorted.length ? sorted[i + 1][0] : lineLen;
      add(sorted[i].length >= 4 ? normalize(map.sources[sorted[i][1]]) : '<unmapped>', Math.max(0, end - sorted[i][0]));
    }
  }
  for (let li = 0; li < lineTexts.length; li++) {
    if (!lines[li]?.length) add('<unmapped>', lineTexts[li].length + 1);
  }

  const files = [...bySource].map(([source, bytes]) => ({ source, bytes })).sort((a, b) => b.bytes - a.bytes);

  const byDomain = new Map();
  for (const r of files) {
    const m = /^libs\/([^/]+)\/src\/lib\/([^/]+)/.exec(r.source);
    const key = m
      ? `${m[1]}/${m[2]}`
      : r.source.startsWith('libs/')
        ? r.source.split('/').slice(0, 2).join('/')
        : r.source;
    byDomain.set(key, (byDomain.get(key) ?? 0) + r.bytes);
  }

  const outKey = Object.keys(min.metafile.outputs).find((k) => k.endsWith('.js'));
  const metafileInputs = Object.entries(min.metafile.outputs[outKey].inputs)
    .map(([file, v]) => ({ file, bytes: v.bytesInOutput }))
    .sort((a, b) => b.bytes - a.bytes);

  return {
    name,
    code,
    raw: out.byteLength,
    gz,
    files,
    domains: [...byDomain].map(([domain, bytes]) => ({ domain, bytes })).sort((a, b) => b.bytes - a.bytes),
    metafileInputs,
  };
};

const main = async () => {
  const cacheDir = assertOutsideRepo(
    resolve(arg('cache', join(OUT_ROOT, `linked-sm-${await distFingerprint(distLibs)}`))),
    'linked-FESM cache',
  );
  await mkdir(cacheDir, { recursive: true });
  await mkdir(outDir, { recursive: true });
  process.stderr.write(`dist:  ${distLibs}\ncache: ${cacheDir}\nout:   ${outDir}\n`);
  const aliases = await processPackages(distLibs, cacheDir, { sourceMaps: true });
  const workDir = join(cacheDir, 'entries');
  await mkdir(workDir, { recursive: true });

  const entriesFile = arg('entries');
  const entries = entriesFile
    ? JSON.parse(await readFile(resolve(entriesFile), 'utf8'))
    : { [arg('name', 'entry')]: arg('entry') };
  if (!entriesFile && !arg('entry')) throw new Error('pass --entry "<code>" or --entries <file.json>');

  const results = [];
  for (const [name, code] of Object.entries(entries)) {
    const dump = arg('dump')
      ? outPath(Object.keys(entries).length > 1 ? `${name}-${arg('dump')}` : arg('dump'))
      : undefined;
    const r = await decompose(name, code, aliases, workDir, { dump });
    results.push(r);
    const total = r.files.reduce((a, x) => a + x.bytes, 0);
    console.log(`\n=== ${name} — ${(r.raw / 1024).toFixed(1)} kB min / ${(r.gz / 1024).toFixed(1)} kB gz`);
    console.log(`--- top ${topN} source files (minified bytes, sourcemap-attributed)`);
    for (const row of r.files.slice(0, topN)) {
      console.log(
        `${String(row.bytes).padStart(8)}  ${((row.bytes / total) * 100).toFixed(1).padStart(5)}%  ${row.source}`,
      );
    }
    console.log(`--- top ${topN} domains`);
    for (const row of r.domains.slice(0, topN)) {
      console.log(
        `${String(row.bytes).padStart(8)}  ${((row.bytes / total) * 100).toFixed(1).padStart(5)}%  ${row.domain}`,
      );
    }
    console.log('--- per input (esbuild metafile)');
    for (const row of r.metafileInputs) console.log(`${String(row.bytes).padStart(8)}         ${row.file}`);
    if (dump) console.log(`--- unminified bundle written to ${dump}`);
  }
  if (arg('json')) {
    const p = outPath(arg('json'));
    await writeFile(p, JSON.stringify(results, null, 2), 'utf8');
    console.log(`\nwrote ${p}`);
  }
};

await main();
