import { readFileSync } from 'fs';
import { join } from 'path';
import { resolveContentRoot } from '../load-content';
import { EmitContext, EmittedFile } from './shared';

export const CLAUDE_SETTINGS_FILE = '.claude/settings.json';

const HOOKS_DIR = '.claude/hooks/ethlete';

type HookDefinition = { event: string; file: string; timeout: number };

/**
 * Hooks a repo can opt into via the config's `hooks` array. Hooks run arbitrary commands on the
 * developer's machine, so unlike rules and skills they are never emitted by default.
 */
export const CLAUDE_HOOKS: Record<string, HookDefinition> = {
  'context-warning': { event: 'UserPromptSubmit', file: 'context-warning.py', timeout: 10 },
};

export const assertKnownHooks = (hooks: string[]) => {
  const unknown = hooks.filter((name) => !(name in CLAUDE_HOOKS));

  if (unknown.length > 0) {
    throw new Error(`Unknown hook(s): ${unknown.join(', ')}. Known hooks: ${Object.keys(CLAUDE_HOOKS).join(', ')}.`);
  }
};

const commandFor = (file: string) => `python3 "$CLAUDE_PROJECT_DIR/${HOOKS_DIR}/${file}"`;

/** `#` comment instead of the HTML banner, placed after the shebang so the file stays runnable. */
const withBanner = (raw: string, version: string) => {
  const banner = `# Generated by @ethlete/agent-rules v${version} — DO NOT EDIT. Run \`npx ethlete-agents sync\`.`;
  const lines = raw.split('\n');

  if (lines[0]?.startsWith('#!')) return [lines[0], banner, ...lines.slice(1)].join('\n');

  return `${banner}\n${raw}`;
};

type HookCommand = { type?: string; command?: string; timeout?: number };
type HookGroup = { hooks?: HookCommand[] };
type Settings = Record<string, unknown> & { hooks?: Record<string, HookGroup[]> };

const isGenerated = (hook: HookCommand) => (hook.command ?? '').includes(HOOKS_DIR);

/**
 * Rewrites the generated entries in `.claude/settings.json` declaratively: every entry pointing
 * into `.claude/hooks/ethlete/` is dropped and the currently enabled hooks are re-added, so
 * disabling a hook in the config also unregisters it. Everything else in the file is untouched.
 */
export const mergeClaudeSettings = (options: { existing: string; hooks: string[] }) => {
  const { existing, hooks } = options;
  const settings = JSON.parse(existing.trim() || '{}') as Settings;
  const events = { ...(settings.hooks ?? {}) };

  for (const [event, groups] of Object.entries(events)) {
    const kept = groups
      .map((group) => ({ ...group, hooks: (group.hooks ?? []).filter((hook) => !isGenerated(hook)) }))
      .filter((group) => group.hooks.length > 0);

    if (kept.length > 0) events[event] = kept;
    else delete events[event];
  }

  for (const name of hooks) {
    const definition = CLAUDE_HOOKS[name];

    if (!definition) continue;

    events[definition.event] = [
      ...(events[definition.event] ?? []),
      { hooks: [{ type: 'command', command: commandFor(definition.file), timeout: definition.timeout }] },
    ];
  }

  if (Object.keys(events).length > 0) settings.hooks = events;
  else delete settings.hooks;

  return `${JSON.stringify(settings, null, 2)}\n`;
};

/**
 * The hook scripts plus the settings registration. Runs even when the claude target is off so a
 * repo that drops the target also gets its stale registrations removed — the settings file is
 * only planned when its parsed content actually changes, and an unparseable file is left alone.
 */
export const emitClaudeHooks = (options: {
  context: EmitContext;
  claudeTarget: boolean;
  existingSettings: string;
}): EmittedFile[] => {
  const { context, claudeTarget, existingSettings } = options;
  const hooks = claudeTarget ? context.hooks : [];
  const files: EmittedFile[] = [];

  for (const name of hooks) {
    const definition = CLAUDE_HOOKS[name];

    if (!definition) continue;

    const raw = readFileSync(join(resolveContentRoot(), 'hooks', definition.file), 'utf8');

    files.push({ path: `${HOOKS_DIR}/${definition.file}`, contents: withBanner(raw, context.version) });
  }

  try {
    const merged = mergeClaudeSettings({ existing: existingSettings, hooks });

    if (JSON.stringify(JSON.parse(existingSettings.trim() || '{}')) !== JSON.stringify(JSON.parse(merged))) {
      files.push({ path: CLAUDE_SETTINGS_FILE, contents: merged });
    }
  } catch {
    // Unparseable settings.json — never clobber a file the repo owns.
  }

  return files;
};
