import { readFileSync } from 'fs';
import { join } from 'path';
import { resolveContentRoot } from '../load-content';
import { removeMarkedBlock, replaceMarkedBlock } from '../render';
import { EmittedFile } from './shared';

export const HUSKY_DIR = '.husky';

export const START_MARKER = '# ethlete:git-flow:start';
export const END_MARKER = '# ethlete:git-flow:end';

/**
 * Git hooks a repo can opt into via the config's `gitHooks` array. Like the agent hooks these never
 * default: a generated block that can reject a developer's push is a higher-stakes artifact than a
 * markdown one, so a repo asks for it.
 */
export const KNOWN_GIT_HOOKS: Record<string, { file: string }> = {
  'pre-push': { file: 'pre-push.sh' },
  'post-checkout': { file: 'post-checkout.sh' },
};

export const assertKnownGitHooks = (hooks: string[]) => {
  const unknown = hooks.filter((name) => !(name in KNOWN_GIT_HOOKS));

  if (unknown.length > 0) {
    throw new Error(
      `Unknown git hook(s): ${unknown.join(', ')}. Known git hooks: ${Object.keys(KNOWN_GIT_HOOKS).join(', ')}.`,
    );
  }
};

export const huskyHookPath = (name: string) => `${HUSKY_DIR}/${name}`;

const SHEBANG = '#!/bin/sh\n';

const block = (options: { file: string; version: string }) => {
  const { file, version } = options;
  const body = readFileSync(join(resolveContentRoot(), 'git-hooks', file), 'utf8');

  return [
    `# Generated by @ethlete/agent-rules v${version} — DO NOT EDIT between the markers. Run \`npx ethlete-agents sync\`.`,
    '# Set ETHLETE_GIT_FLOW_SKIP=1 to silence it on this machine.',
    body.trimEnd(),
  ].join('\n');
};

/**
 * Appends the check to whatever the repo already has in `.husky/<name>`, between markers — those
 * files routinely hold a git-lfs hook that must keep running and must keep reading stdin first,
 * which is why the appended block never consumes it.
 */
export const emitGitHooks = (options: {
  gitHooks: string[];
  version: string;
  huskyExists: boolean;
  existing: Record<string, string>;
}): EmittedFile[] => {
  const { gitHooks, version, huskyExists, existing } = options;

  if (!huskyExists) return [];

  return Object.entries(KNOWN_GIT_HOOKS).flatMap(([name, definition]) => {
    const path = huskyHookPath(name);
    const current = existing[name] ?? '';

    if (!gitHooks.includes(name)) {
      const stripped = removeMarkedBlock({ existing: current, startMarker: START_MARKER, endMarker: END_MARKER });

      return stripped === current ? [] : [{ path, contents: stripped.trim().length > 0 ? stripped : SHEBANG }];
    }

    return [
      {
        path,
        contents: replaceMarkedBlock({
          existing: current.trim().length > 0 ? current : SHEBANG,
          block: block({ file: definition.file, version }),
          startMarker: START_MARKER,
          endMarker: END_MARKER,
        }),
      },
    ];
  });
};
