import { defineCall } from '@design-explore';

export default defineCall({
  eyebrow: 'Kerbe · call 6',
  headline: 'How the break says it is a break',
  intro:
    'Call 5 made the break a frame: two hairlines, no fill. This call asks how a reader knows that a stretch of day is a break. Every frame draws the same day. Three agent runs cross the 12:15 break, one per lane, so no lane is idle through it. The 15:30 break is 15m and keeps every lane idle. Each option has to hold both.',
  frameWidth: 1100,
  rounds: [
    {
      key: 'r1',
      title: 'The word inside the lanes',
      note: 'A label in the band area, on whatever ground it needs to stay readable. All three lost: a plate under the word is a fill, and a fill is what call 5 threw out.',
    },
    {
      key: 'r2',
      title: 'Mark the break, drop the word',
      note: 'D, E and F draw in the gutter, at its left edge, where no band can ever reach. G, H and I try a pattern instead of a line: G is D with a texture, H puts the pattern in the rules themselves, and I runs a hatch across the whole day, over the bands, which re-opens call 5. All six came out too quiet.',
    },
    {
      key: 'r3',
      title: 'The same three ideas, turned up',
      note: 'The hatch takes the whole gutter, the frame goes heavy and cuts the lane lines, and the hatch across the day goes coarse. K holds, but a mark alone never says the word "break".',
    },
    {
      key: 'r4',
      title: 'K, put back together with a name',
      note: 'The word in the gutter, then that word over J, over L, and turned down the gutter. N won. Two faults came out of it: the word is pinned to the top, so a 15m break is nearly all word, and a word has to be translated.',
    },
    {
      key: 'r5',
      title: 'A sign in place of the word',
      note: 'N with a sign centred in the block instead, so it needs no translation and sits in the middle of a 15m break. Q won on the sign, and the bars read as noise on the hatch.',
    },
    {
      key: 'r6',
      title: 'How the sign sits on the hatch',
      note: 'Three ways to keep the sign off the pattern behind it: its own ground, cut out of the hatch, or weight alone. T won. U only interrupts hairline strokes, so the sign nearly disappears.',
    },
    {
      key: 'r7',
      title: 'T, and the 15m break',
      note: 'Two faults in T, both fixed in every frame here: the bars were 2px with a 3.5px gap, which centres the pair on a half pixel and renders one bar wider, and at 15m the plate overran the rules. W won: the sign shrinks and keeps its ground, so the plate that T was chosen for survives the short break. X drops the plate at 15m and puts the bars back on the hatch, which is the noise T was drawn to fix.',
    },
  ],
  options: [
    {
      key: 'a',
      round: 'r1',
      name: 'A · The label carries its own ground',
      claim:
        'It straddles the top hairline and cuts a gap in it, on a small plate of ground, so it reads over anything behind it and needs nothing computed.',
      cost: 'The plate covers a slice of whatever band it lands on, and one band always loses a few pixels of its top row.',
      verdict: 'rejected',
      load: () => import('./option-a'),
    },
    {
      key: 'b',
      round: 'r1',
      name: 'B · The label takes the first idle lane',
      claim: 'It goes where the day is empty, so it covers nothing at all.',
      cost: 'Its column moves from break to break, and when every lane is busy it has no home and falls back to the gutter.',
      verdict: 'rejected',
      load: () => import('./option-b'),
    },
    {
      key: 'c',
      round: 'r1',
      name: 'C · The label stays in the gutter',
      claim: 'The band area is never touched. This is what the app does today.',
      cost: 'The gutter is 5rem, so the word goes and only the length is left, and a break on the hour meets an hour label.',
      verdict: 'rejected',
      load: () => import('./option-c'),
    },
    {
      key: 'd',
      round: 'r2',
      name: 'D · The clock is notched',
      claim:
        'The two rules turn into the gutter and close on a stroke at its left edge, so the break is a bracket cut into the clock. It is three lines, no fill, and its height is the length.',
      cost: 'It carries no word, so the first reading has to be learned, and a 15m break is 2rem of bracket.',
      verdict: 'rejected',
      load: () => import('./option-d'),
    },
    {
      key: 'e',
      round: 'r2',
      name: 'E · A mark in the gutter',
      claim:
        'A pause sign sits in the gutter, centred on the break. It is one fixed size in one fixed place, and it names the break as a sign instead of a word.',
      cost: 'The mark does not measure the break, so only the rules say how long it ran, and a sign is one more thing to learn.',
      verdict: 'rejected',
      load: () => import('./option-e'),
    },
    {
      key: 'f',
      round: 'r2',
      name: 'F · The two rules alone',
      claim:
        'Nothing is added. A stretch of day between two hairlines is a break, and the frame from call 5 is all of it.',
      cost: 'A break that holds three agent bands then looks like any other stretch of day, and nothing tells the reader which one it is.',
      verdict: 'rejected',
      load: () => import('./option-f'),
    },
    {
      key: 'g',
      round: 'r2',
      name: 'G · The notch is hatched',
      claim:
        'D again, with a texture in place of the empty bracket. A hatch is the drawing convention for a stretch that is out of play, so it names the break without a word and still measures it.',
      cost: 'At 15m the column is 2rem tall and 1.2rem wide, which holds about four strokes, so the pattern barely reads.',
      verdict: 'rejected',
      load: () => import('./option-g'),
    },
    {
      key: 'h',
      round: 'r2',
      name: 'H · The rules are dashed',
      claim:
        'The frame says it in its own line: an hour line is solid, a break edge is dashed. Nothing new is added anywhere, and no area is spent.',
      cost: 'A 1px dash is light, so the alpha goes up to hold the weight, and a dashed line elsewhere in the app can no longer mean anything else.',
      verdict: 'rejected',
      load: () => import('./option-h'),
    },
    {
      key: 'i',
      round: 'r2',
      name: 'I · The day is hatched across',
      claim:
        'A faint hatch spans every lane between the two rules, over the bands as well as the ground. It runs through the work, so it reads as the day and not as a claim that one lane was idle.',
      cost: 'It re-opens what call 5 settled, and it lays a texture over content.',
      verdict: 'rejected',
      load: () => import('./option-i'),
    },
    {
      key: 'j',
      round: 'r3',
      name: 'J · The gutter is a block',
      claim:
        'The hatch takes the whole 5rem gutter, not a 1.2rem strip of it, and the hour labels stay on top of it. It is four times the width of D and still touches no band.',
      cost: 'The clock column now carries two jobs, and a break that crosses an hour puts a label on a pattern.',
      verdict: 'rejected',
      load: () => import('./option-j'),
    },
    {
      key: 'k',
      round: 'r3',
      name: 'K · The frame goes heavy and the grid opens',
      claim:
        'The two rules go to 2px and run from the gutter to the right edge, and the lane lines stop between them. For those minutes the day has no columns, which is what a break is.',
      cost: 'Two heavy rules are the loudest thing on a quiet day, and the cut lane lines cost a pixel out of the grid.',
      verdict: 'chosen',
      load: () => import('./option-k'),
    },
    {
      key: 'l',
      round: 'r3',
      name: 'L · The hatch turns up',
      claim: 'I again, at a weight you cannot miss: a coarse hatch over every lane and over the bands.',
      cost: 'It re-opens call 5, and the texture runs over the band labels.',
      verdict: 'rejected',
      load: () => import('./option-l'),
    },
    {
      key: 'm',
      round: 'r4',
      name: 'M · K, and it says the word',
      claim:
        'K, with "BREAK" in the gutter, inside the frame, set like an hour label. The word left the lanes, so it needs no ground of its own, and 5rem holds it once the length is gone.',
      cost: 'The word sits at the top, so it says nothing about how long the break ran.',
      verdict: 'rejected',
      load: () => import('./option-m'),
    },
    {
      key: 'n',
      round: 'r4',
      name: 'N · M, on the hatched gutter',
      claim: 'M with J behind it: the gutter is hatched between the rules, and the word sits on the hatch.',
      cost: 'The pattern runs under 1.05rem type, which is the smallest type on the screen.',
      verdict: 'chosen',
      load: () => import('./option-n'),
    },
    {
      key: 'o',
      round: 'r4',
      name: 'O · M, with the day hatched',
      claim: 'M with L across the lanes: the word names it, and the hatch carries it over the whole day.',
      cost: 'Same as L. It re-opens call 5, and the texture runs over the band labels.',
      verdict: 'rejected',
      load: () => import('./option-o'),
    },
    {
      key: 'p',
      round: 'r4',
      name: 'P · M, with the word turned',
      claim:
        'The word runs down the gutter instead of across it, so it grows with the break and can never meet an hour label.',
      cost: 'A 15m break is 2rem, which cuts the word, and turned type is slower to read.',
      verdict: 'rejected',
      load: () => import('./option-p'),
    },
    {
      key: 'q',
      round: 'r5',
      name: 'Q · N, with a pause sign',
      claim:
        'N with a sign in place of the word, centred in the block instead of pinned to its top. It needs no translation, and at 15m it still sits in the middle of 2rem.',
      cost: 'A pause sign is borrowed from a player, where it means a thing that was stopped by hand.',
      verdict: 'chosen',
      load: () => import('./option-q'),
    },
    {
      key: 'r',
      round: 'r5',
      name: 'R · N, with a cup',
      claim: 'The same place and the same size, with the sign everybody already reads as a break.',
      cost: 'It names a coffee, and a break is any time away from the machine.',
      verdict: 'rejected',
      load: () => import('./option-r'),
    },
    {
      key: 's',
      round: 'r5',
      name: 'S · N, with nothing in the block',
      claim:
        'The hatched block, the heavy frame and the open grid, and no sign at all. At 15m it is two clean rem of pattern.',
      cost: 'Nothing names the break, so the pattern has to be learned once.',
      verdict: 'rejected',
      load: () => import('./option-s'),
    },
    {
      key: 't',
      round: 'r6',
      name: 'T · The sign gets its own ground',
      claim: 'Q, with the hatch stopped under the bars, the same way an hour label carries its ground.',
      cost: 'A plate inside the block is a second shape to place, and at 15m it leaves 0.1rem to each rule.',
      verdict: 'chosen',
      load: () => import('./option-t'),
    },
    {
      key: 'u',
      round: 'r6',
      name: 'U · The sign is cut out of the hatch',
      claim:
        'The bars are drawn in the ground, so the sign is a hole in the pattern and not a mark on it. That is what the brand is named after.',
      cost: 'It reads only where the hatch runs behind it, so the sign and the block can never be separated.',
      verdict: 'rejected',
      load: () => import('./option-u'),
    },
    {
      key: 'v',
      round: 'r6',
      name: 'V · The sign gets weight',
      claim: 'No plate and no cut: 3px bars at full ink, which is the one thing in the gutter that is not a hairline.',
      cost: 'The hatch still runs between the bars, so the sign stays busier than the word it replaced.',
      verdict: 'rejected',
      load: () => import('./option-v'),
    },
    {
      key: 'w',
      round: 'r7',
      name: 'W \u00b7 T, and the sign shrinks at 15m',
      claim:
        'Under 3rem the bars drop to 8px and the plate halves its padding, so the plate keeps 4px clear of each rule. The sign is one shape at two sizes.',
      cost: 'The same sign now has two sizes, and the smaller one is 8px of bar.',
      verdict: 'chosen',
      load: () => import('./option-w'),
    },
    {
      key: 'x',
      round: 'r7',
      name: 'X \u00b7 T, and the plate goes at 15m',
      claim:
        'The bars keep one size everywhere. Under 3rem they lose the ground and sit straight on the hatch, which is only 2rem of pattern there.',
      cost: 'The sign then reads two ways, and on the short break it is back to the noise T was drawn to fix.',
      verdict: 'rejected',
      load: () => import('./option-x'),
    },
  ],
});
