#!/usr/bin/env python3
# Generated by @ethlete/agent-rules — DO NOT EDIT. Run `npx ethlete-agents sync`.
"""UserPromptSubmit hook: warn when the context window is getting large.

Reads the hook input JSON from stdin, estimates the current context size from
the session transcript, and emits a warning (visible to both the user and the
agent) when it crosses a threshold. Recommends the handoff skill so work can
continue in a fresh session.

Runs under both Claude Code and Codex, selected by `--agent` on the command
line rather than sniffed from the payload — the generator writes the flag, so
the two never have to be told apart at runtime. The two differ in three ways
that matter here, all captured in AGENT_PROFILES:

  * Transcript format. Claude writes one JSON object per message with
    `message.usage`; Codex writes a rollout stream whose `token_count` events
    carry a TokenUsageInfo. Codex's rollout format is explicitly not a stable
    interface, so the parser searches each line for the usage object instead of
    walking a fixed path.
  * Context budget. Claude's budget is capped at its 200k long-context pricing
    boundary. Codex uses the model-specific pricing boundary where OpenAI
    documents one, and the reported window otherwise. Crossing either boundary
    costs far more than handing off into a fresh session ever would.
  * How a handoff is invoked. Claude has a slash command and /clear; Codex has
    neither and reads the skill from disk. The skill's own name differs per repo
    (`ethlete-handoff` where the generator installed it, `handoff` where the repo
    ships its own copy), so it is resolved at runtime — see handoff_skill().

At the critical tier, if the session's permission_mode is "auto", the
instruction escalates from "recommend" to "just do it": auto mode already
means the user wants the agent acting without stopping to ask, and clearing +
resuming can't be triggered programmatically (no hook or tool can submit
input to a running session), so the best available automation is to save the
handoff file itself immediately rather than waiting for a natural stopping
point. Codex's permission_mode value set is undocumented, so its profile lists
no auto modes and the escalation stays off there.

Warns once per tier per session (state kept in a temp file); re-arms itself
if the context shrinks again (e.g. after a compaction).

Can be disabled per machine via a gitignored ethlete-agents.config.local.json
at the repo root: {"disableHooks": true} or {"disableHooks": ["context-warning"]}.
To keep the tiered warnings but drop just the auto-mode auto-save escalation,
use {"disableAutoHandoffSave": true} instead - the critical tier then falls
back to recommending a handoff, same as non-auto mode.

Fail-safe: any error exits 0 with no output — the hook must never block a prompt.
"""

import json
import os
import sys
import tempfile

HOOK_NAME = "context-warning"
LOCAL_CONFIG_FILE = "ethlete-agents.config.local.json"

# Warn / critical fire at these fractions of the token budget.
WARN_FRACTION = 0.70
CRITICAL_FRACTION = 0.85

# On models with a window larger than this, tokens beyond it bill the whole
# context at the long-context premium rate — so the budget never exceeds it.
PREMIUM_BOUNDARY = 200_000

# Codex models whose long-context pricing starts above 272k input tokens. Models
# without that pricing rule use their reported context window instead.
CODEX_PREMIUM_BOUNDARIES = (
    ("gpt-5.6", 272_000),
    ("gpt-5.5", 272_000),
    ("gpt-5.4-mini", None),
    ("gpt-5.4", 272_000),
)

# Context window (tokens) per model, matched by substring against the model id
# from the transcript — first match wins. Edit these as model windows change;
# anything unmatched falls back to DEFAULT_WINDOW.
CONTEXT_WINDOWS = (
    ("opus-5", 1_000_000),
    ("opus-4-8", 1_000_000),
    ("sonnet-4-5", 1_000_000),
    ("sonnet-5", 1_000_000),
    ("fable-5", 1_000_000),
    # Generic fallbacks — keep these last: the first substring match wins, so a bare
    # "opus"/"sonnet" entry placed above would shadow every versioned entry below it.
    ("opus", 200_000),
    ("sonnet", 200_000),
    ("haiku", 200_000),
)
DEFAULT_WINDOW = 200_000

AGENT_PROFILES = {
    "claude": {
        "premium_boundary": PREMIUM_BOUNDARY,
        "premium_boundaries": (),
        # Claude's transcript reports no window, so it is resolved from the model id.
        "default_window": None,
        "auto_modes": ("auto",),
        "emits_system_message": True,
        "act_now": "Run /{handoff} now and continue in a fresh session.",
        "act_later": "consider /{handoff} to continue in a fresh session",
        "recommend": "recommend the user run /{handoff} to save state and start a fresh session",
        "suggest": "suggest the user run /{handoff} to save state and start a fresh session",
        "save_now": (
            "run the handoff skill's save mode right now (finish only an in-flight atomic "
            "edit first, nothing new). Then tell the user exactly which handoff file was "
            "written and that they should run /clear, then '/{handoff} resume <slug>', to "
            "continue — clearing and resuming can't be done programmatically, so this is "
            "the one step still on them."
        ),
    },
    "codex": {
        "premium_boundary": None,
        "premium_boundaries": CODEX_PREMIUM_BOUNDARIES,
        # Only reached if a rollout omits model_context_window; the CONTEXT_WINDOWS table
        # holds Claude model ids and would never match a Codex one.
        "default_window": 272_000,
        # Codex's permission_mode values are undocumented; until one is confirmed to mean
        # "never ask", no value enables the auto-save escalation.
        "auto_modes": (),
        # Only hookSpecificOutput.additionalContext is documented for Codex, so the
        # user-facing line is folded into the model-facing text instead.
        "emits_system_message": False,
        "act_now": "Save a handoff now and continue in a fresh session.",
        "act_later": "consider saving a handoff and continuing in a fresh session",
        "recommend": (
            "tell the user you are near the context limit, then follow "
            ".agents/skills/{handoff}/SKILL.md to save a handoff and have them start a "
            "fresh session"
        ),
        "suggest": (
            "suggest saving a handoff via .agents/skills/{handoff}/SKILL.md and "
            "continuing in a fresh session"
        ),
        "save_now": (
            "follow .agents/skills/{handoff}/SKILL.md and save a handoff right now "
            "(finish only an in-flight atomic edit first, nothing new). Then tell the user "
            "exactly which handoff file was written and that they should start a fresh "
            "codex session and resume from it."
        ),
    },
}


def handoff_skill(root):
    """Name of the handoff skill installed in this repo.

    The generator prefixes every skill it writes, so the command is /ethlete-handoff in a
    consumer repo — but a repo that excludes the generated copy and ships its own (the SDK
    itself) has a plain /handoff instead. Naming the wrong one sends the user to a slash
    command that does not exist, so it is read off disk rather than assumed.
    """
    for name in ("ethlete-handoff", "handoff"):
        for skills_dir in (".claude/skills", ".agents/skills"):
            if os.path.isdir(os.path.join(root or ".", skills_dir, name)):
                return name
    return "ethlete-handoff"


def resolve_profile(profile, skill):
    """Fills the installed handoff skill's name into a profile's message fragments."""
    return {
        key: value.replace("{handoff}", skill) if isinstance(value, str) else value
        for key, value in profile.items()
    }


def agent_name(argv):
    """The --agent value, defaulting to claude — older registrations pass no flag."""
    for index, arg in enumerate(argv):
        if arg == "--agent" and index + 1 < len(argv):
            return argv[index + 1]
        if arg.startswith("--agent="):
            return arg.split("=", 1)[1]
    return "claude"


def repo_root(data):
    """Repo root: the env var the agent sets, else derived from this script's own location.

    The script always lives at <root>/.<agent>/hooks/ethlete/context-warning.py, so walking
    four levels up works for any agent that has no project-dir variable of its own.
    """
    for variable in ("CLAUDE_PROJECT_DIR", "CODEX_PROJECT_DIR"):
        value = os.environ.get(variable)
        if value:
            return value
    here = os.path.abspath(__file__)
    derived = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(here))))
    if os.path.isfile(os.path.join(derived, LOCAL_CONFIG_FILE)):
        return derived
    cwd = data.get("cwd")
    return cwd if isinstance(cwd, str) and cwd else derived


def load_local_config(root):
    """Parsed ethlete-agents.config.local.json at the repo root, or {} if missing/unreadable."""
    if not root:
        return {}
    try:
        with open(os.path.join(root, LOCAL_CONFIG_FILE), encoding="utf-8") as f:
            config = json.load(f)
    except (OSError, ValueError, AttributeError):
        return {}
    return config if isinstance(config, dict) else {}


def disabled_locally(config):
    """True when the local config disables this hook (or all hooks) on this machine."""
    disabled = config.get("disableHooks")
    return disabled is True or (isinstance(disabled, list) and HOOK_NAME in disabled)


def auto_handoff_save_disabled(config):
    """True when the local config opts out of the auto-mode critical-tier auto-save."""
    return config.get("disableAutoHandoffSave") is True


def window_for(model):
    """Context window for a model id, by first substring match; DEFAULT_WINDOW otherwise."""
    if model:
        for needle, window in CONTEXT_WINDOWS:
            if needle in model:
                return window
    return DEFAULT_WINDOW


def premium_boundary_for(profile, model):
    """Model-specific pricing boundary, falling back to the agent-wide value."""
    if model:
        for needle, boundary in profile["premium_boundaries"]:
            if needle in model:
                return boundary
    return profile["premium_boundary"]


def claude_context_state(transcript_path):
    """(tokens, model, window) from the last main-chain assistant message.

    tokens ≈ its total input tokens (fresh + cache read + cache creation). Claude reports no
    window in the transcript, so it is resolved from the model id by the caller.
    """
    last_usage = None
    last_model = None
    with open(transcript_path, encoding="utf-8") as f:
        for line in f:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            if obj.get("type") != "assistant" or obj.get("isSidechain"):
                continue
            message = obj.get("message") or {}
            usage = message.get("usage")
            if usage:
                last_usage = usage
                last_model = message.get("model") or last_model
    if not last_usage:
        return 0, last_model, None
    tokens = (
        last_usage.get("input_tokens", 0)
        + last_usage.get("cache_read_input_tokens", 0)
        + last_usage.get("cache_creation_input_tokens", 0)
    )
    return tokens, last_model, None


def find_token_usage_info(node):
    """The deepest TokenUsageInfo-shaped dict in a parsed rollout line, or None.

    Codex documents its rollout format as unstable, so this searches for the shape
    (a dict carrying `last_token_usage`) rather than walking a fixed key path.
    """
    if isinstance(node, dict):
        if isinstance(node.get("last_token_usage"), dict):
            return node
        for value in node.values():
            found = find_token_usage_info(value)
            if found:
                return found
    elif isinstance(node, list):
        for value in node:
            found = find_token_usage_info(value)
            if found:
                return found
    return None


def codex_context_state(transcript_path):
    """(tokens, model, window) from the last token_count event in a Codex rollout.

    tokens is the last request's `total_tokens` — Codex's own `tokens_in_context_window()`
    is exactly that field, and `last_token_usage` is replaced per request while
    `total_token_usage` accumulates across the whole session.
    """
    last_info = None
    last_model = None
    with open(transcript_path, encoding="utf-8") as f:
        for line in f:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            model = (obj.get("payload") or {}).get("model") if isinstance(obj.get("payload"), dict) else None
            if isinstance(model, str) and model:
                last_model = model
            info = find_token_usage_info(obj)
            if info:
                last_info = info
    if not last_info:
        return 0, last_model, None
    usage = last_info.get("last_token_usage") or {}
    window = last_info.get("model_context_window")
    return usage.get("total_tokens", 0), last_model, window if isinstance(window, int) else None


CONTEXT_READERS = {"claude": claude_context_state, "codex": codex_context_state}


def messages(profile, tier, tokens, budget, priced, auto_mode):
    """(systemMessage, additionalContext) for a tier.

    priced: the budget is the pricing boundary, not the window — the reason to
    hand off is cost, not an imminent auto-compact.
    auto_mode: at the critical tier, escalates from "recommend a handoff" to
    "save it now" — see the module docstring for why.
    """
    k = f"~{tokens // 1000}k"
    pct = round(tokens / budget * 100)
    budget_k = f"{budget // 1000}k"

    if priced:
        approach = "about to cross" if tier == 2 else "approaching"
        headline = f"Context is at {k} tokens — {approach} the {budget_k} long-context pricing boundary"
        detail = (
            f"The context is at {k} tokens — {pct}% of the {budget_k} long-context "
            f"pricing boundary."
        )
    else:
        headline = f"Context is at {k} tokens ({pct}% of the {budget_k} window)"
        detail = (
            f"The context window is at {k} tokens — {pct}% of this model's "
            f"{budget_k} window"
        )

    if tier == 2:
        threshold = f" (critical, ≥{int(CRITICAL_FRACTION * 100)}%)"
        detail = detail if priced else f"{detail}{threshold}."
        pressure = (
            "Past it every request is billed at the premium rate. "
            if priced
            else ""
        )
        tail = "" if priced else " — auto-compact is imminent"
        if auto_mode:
            return (
                f"🔴 {headline}{tail}. Auto mode is active: saving a handoff now.",
                f"[context-warning hook] {detail} {pressure}Auto mode is active, so don't "
                f"just recommend a handoff — {profile['save_now']}",
            )
        return (
            f"🔴 {headline}{tail}. {profile['act_now']}",
            f"[context-warning hook] {detail} {pressure}Finish only the immediate step, "
            f"then {profile['recommend']}. Do not start new sub-tasks.",
        )

    threshold = f" (≥{int(WARN_FRACTION * 100)}%)"
    detail = detail if priced else f"{detail}{threshold}."
    pressure = "Past it every request is billed at the premium rate. " if priced else ""
    return (
        f"🟡 {headline}. At the next natural stopping point, {profile['act_later']}.",
        f"[context-warning hook] {detail} {pressure}When the current task reaches a "
        f"natural stopping point, {profile['suggest']}. Keep working normally until then.",
    )


def main():
    agent = agent_name(sys.argv[1:])
    profile = AGENT_PROFILES.get(agent)
    if not profile:
        return

    data = json.load(sys.stdin)
    root = repo_root(data)
    local_config = load_local_config(root)
    if disabled_locally(local_config):
        return

    profile = resolve_profile(profile, handoff_skill(root))

    transcript_path = data.get("transcript_path")
    session_id = data.get("session_id", "unknown")
    auto_mode = data.get("permission_mode") in profile["auto_modes"] and not auto_handoff_save_disabled(local_config)
    if not transcript_path or not os.path.isfile(transcript_path):
        return

    tokens, model, reported_window = CONTEXT_READERS[agent](transcript_path)
    window = reported_window or profile["default_window"] or window_for(model)
    boundary = premium_boundary_for(profile, model)
    budget = min(window, boundary) if boundary else window
    warn_tokens = int(budget * WARN_FRACTION)
    critical_tokens = int(budget * CRITICAL_FRACTION)
    tier = 2 if tokens >= critical_tokens else 1 if tokens >= warn_tokens else 0

    state_file = os.path.join(
        tempfile.gettempdir(), f"{agent}-context-warning-{session_id}"
    )
    prev_tier = 0
    try:
        with open(state_file, encoding="utf-8") as f:
            prev_tier = int(f.read().strip() or 0)
    except (OSError, ValueError):
        pass

    if tier != prev_tier:
        try:
            with open(state_file, "w", encoding="utf-8") as f:
                f.write(str(tier))
        except OSError:
            pass

    if tier <= prev_tier:
        return  # already warned at this tier (or context shrank — state re-armed above)

    system_message, additional_context = messages(
        profile, tier, tokens, budget, budget < window, auto_mode
    )

    if not profile["emits_system_message"]:
        additional_context = f"{additional_context}\n\nTell the user: {system_message}"

    payload = {
        "hookSpecificOutput": {
            "hookEventName": "UserPromptSubmit",
            "additionalContext": additional_context,
        }
    }
    if profile["emits_system_message"]:
        payload["systemMessage"] = system_message
        payload["suppressOutput"] = True

    print(json.dumps(payload))


if __name__ == "__main__":
    try:
        main()
    except Exception:
        pass
    sys.exit(0)
