import { ContentItem } from './load-content';

/**
 * Bodies reference sibling content through tokens rather than hardcoded paths, because the same
 * skill is a namespaced skill under Claude, an `.mdc` rule under Cursor and a plain file path
 * under Codex. Each target supplies its own resolver.
 */
export type LinkResolver = {
  skill: (name: string) => string;
  resource: (options: { skillName: string; fileName: string }) => string;
};

/**
 * `{% … %}`, not `{{ … }}`: content bodies routinely quote Angular templates, and an example
 * containing `{{ count() }}` must not be mistaken for a template token.
 */
const TOKEN_PATTERN = /\{%\s*([a-zA-Z0-9_:.-]+)\s*%\}/g;

export const START_MARKER = '<!-- ethlete:agent-rules:start -->';
export const END_MARKER = '<!-- ethlete:agent-rules:end -->';

export const buildBanner = (version: string) =>
  `<!-- Generated by @ethlete/agent-rules v${version} — DO NOT EDIT. Run \`npx ethlete-agents sync\`. -->`;

const renderValue = (value: string | string[]) =>
  Array.isArray(value) ? value.map((entry) => `\`${entry}\``).join(', ') : value;

export const renderBody = (options: {
  item: ContentItem;
  vars: Record<string, string | string[]>;
  links: LinkResolver;
}) => {
  const { item, vars, links } = options;

  const rendered = item.body.replace(TOKEN_PATTERN, (match, token: string) => {
    const [namespace, argument] = token.split(':');

    if (namespace === 'skill' && argument) return links.skill(argument);

    if (namespace === 'resource' && argument) {
      return links.resource({ skillName: item.frontmatter.name, fileName: argument });
    }

    const value = vars[token];

    if (value === undefined) {
      throw new Error(`${item.frontmatter.name}: no value for template token "${match}".`);
    }

    return renderValue(value);
  });

  const leftover = /\{%[^%]*%\}/.exec(rendered);

  if (leftover) {
    throw new Error(`${item.frontmatter.name}: unresolved template token "${leftover[0]}".`);
  }

  return rendered;
};

/** Variable substitution only — for text that has no business linking to other content. */
export const substituteVars = (options: { text: string; vars: Record<string, string | string[]>; origin: string }) => {
  const { text, vars, origin } = options;

  return text.replace(TOKEN_PATTERN, (match, token: string) => {
    if (token.includes(':')) {
      throw new Error(`${origin}: "${match}" — skill and resource links only work in a SKILL.md body.`);
    }

    const value = vars[token];

    if (value === undefined) {
      throw new Error(`${origin}: no value for template token "${match}".`);
    }

    return renderValue(value);
  });
};

export const renderDescription = (options: { item: ContentItem; vars: Record<string, string | string[]> }) =>
  substituteVars({
    text: options.item.frontmatter.description,
    vars: options.vars,
    origin: `${options.item.frontmatter.name} (description)`,
  });

/**
 * Rewrites the block between the markers, leaving everything a repo wrote around it untouched.
 * A file without markers gets the block appended.
 */
export const replaceMarkedBlock = (options: { existing: string; block: string }) => {
  const { existing, block } = options;
  const wrapped = `${START_MARKER}\n${block}\n${END_MARKER}`;
  const start = existing.indexOf(START_MARKER);
  const end = existing.indexOf(END_MARKER);

  if (start === -1 || end === -1 || end < start) {
    const separator = existing.trim().length > 0 ? `${existing.trimEnd()}\n\n` : '';

    return `${separator}${wrapped}\n`;
  }

  return `${existing.slice(0, start)}${wrapped}${existing.slice(end + END_MARKER.length)}`;
};
