/*
 * Auto-generated by @ethlete/core:tailwind-4-surface-theme
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * Regenerate by running:
 * nx g @ethlete/core:tailwind-4-surface-theme --themesPath=apps/ethlete-studio/src/surface-themes.ts --outputPath=apps/ethlete-studio/src/styles/surface-themes.css
 */

declare module '@ethlete/core' {
  interface EthleteSurfaceThemeNameRegistry {
    name: 'dark' | 'dark-elevated' | 'dark-elevated-2';
  }
}

export {};
