/*
 * Auto-generated by @ethlete/core:tailwind-4-color-theme
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * Regenerate by running:
 * nx g @ethlete/core:tailwind-4-color-theme --themesPath=apps/ethlete-studio/src/themes.ts --outputPath=apps/ethlete-studio/src/styles/themes.css
 */

declare module '@ethlete/core' {
  interface EthleteColorThemeNameRegistry {
    name: 'brand' | 'danger';
  }
}

export {};
