/*
 * Auto-generated by @ethlete/core:tailwind-4-color-theme
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * Regenerate by running:
 * nx g @ethlete/core:tailwind-4-color-theme --themesPath=apps/playground/src/themes.ts --outputPath=apps/playground/src/styles/themes.css
 */

declare module '@ethlete/core' {
  interface EthleteColorThemeNameRegistry {
    name: 'brand' | 'danger' | 'success' | 'warning' | 'neutral' | 'neutral-dark';
  }
}

export {};
