/// Every command `lib.rs` registers, sorted.
///
/// Naming a command here turns it into an `allow-<command>` permission that a capability must grant,
/// so a command left out of this list - or out of `capabilities/default.json` - is refused for every
/// window. A test in `lib.rs` fails when the three lists drift apart.
const COMMANDS: &[&str] = &[
    "agent_log_lines",
    "agent_logs",
    "agent_reply",
    "agent_session_cursors",
    "agent_status",
    "app_settings",
    "call_events",
    "call_source_status",
    "collection_set_paused",
    "collection_state",
    "compacted_through",
    "day_nudge_record",
    "day_review_edits",
    "day_review_edits_between",
    "events_append",
    "events_between",
    "events_by_source",
    "events_delete_before",
    "events_oldest_at",
    "events_set_titles",
    "events_titles_after",
    "git_changes",
    "git_repos",
    "http_request",
    "ingest_events",
    "ingest_status",
    "ledger_entries_for_day",
    "ledger_remove",
    "ledger_upsert",
    "lock_state",
    "lock_window",
    "notify",
    "oauth_authorize",
    "read_spec",
    "reporter_vsix_path",
    "run_process",
    "secret_delete",
    "secret_has",
    "secret_read",
    "secret_write",
    "set_app_settings",
    "set_compacted_through",
    "set_day_nudge_record",
    "set_day_review_edits",
    "set_tempo_coverage",
    "tempo_coverage_for_day",
    "timer_label",
    "timer_running",
    "timer_runs_between",
    "timer_start",
    "timer_stop",
    "tray_set_readout",
    "unlock_window",
    "widget_close",
    "widget_is_open",
    "widget_open",
    "widget_reveal_app",
    "window_capabilities",
    "window_events",
    "window_request_accessibility",
    "window_source_status",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("tauri-build failed");
}
