import { RemovedExport } from '../removed-exports/removed-exports.js';

const NAMES = [
  'PixelRect',
  'GridGeometry',
  'ResizeSpanBounds',
  'computeGeometry',
  'spanWidth',
  'spanHeight',
  'positionToPixelRect',
  'rowsToPixelHeight',
  'pixelRectsEqual',
  'positionsEqual',
  'SNAP_HYSTERESIS',
  'hysteresisRound',
  'resizeSpanBounds',
  'clampResizeRect',
  'snapResizeSpan',
  'projectDragCell',
  'FindCollisionOptions',
  'AutoPlaceOptions',
  'ClampPositionOptions',
  'ResolveCollisionsOptions',
  'RowFloors',
  'CompactLayoutOptions',
  'itemsCollide',
  'findCollision',
  'compactLayout',
  'autoPlace',
  'clampPosition',
  'resolveCollisions',
  'computeGridHeight',
  'MapLayoutOptions',
  'resolveBreakpoint',
  'mapLayoutToBreakpoint',
  'AutoScrollPointer',
  'AutoScroller',
  'findScrollableAncestor',
  'createAutoScroller',
] as const;

export const GRID_ENGINE_INTERNALS_REMOVALS: readonly RemovedExport[] = NAMES.map((name) => ({
  name,
  todo: `${name} is no longer exported; the grid layout engine is internal. Use the GridComponent inputs and outputs, createGridAdapter, or serializeGridLayout / deserializeGridLayout instead.`,
}));
