import { readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { describe, expect, it } from 'vitest';
import { collectEtClasses } from './report';

const COMPONENTS_SRC = join(__dirname, '../../../components/src');

const componentStyleSheets = (dir: string): string[] =>
  readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);

    if (entry.isDirectory()) return entry.name === 'stories' ? [] : componentStyleSheets(path);

    return entry.name.endsWith('.css') ? [path] : [];
  });

const renderModule = (classes: readonly string[]) =>
  [
    '// Generated by components-classes.spec.ts from libs/components/src/**/*.css. Run the spec with `-u` to update.',
    'export const COMPONENTS_CLASSES: readonly string[] = [',
    ...classes.map((name) => `  '${name}',`),
    '];',
    '',
  ].join('\n');

describe('migrate-from-cdk -> COMPONENTS_CLASSES', () => {
  it('lists every et- class a components stylesheet defines', async () => {
    const sheets = componentStyleSheets(COMPONENTS_SRC).sort((a, b) =>
      relative(COMPONENTS_SRC, a).localeCompare(relative(COMPONENTS_SRC, b)),
    );
    const classes = new Set(
      sheets.flatMap((sheet) => collectEtClasses(readFileSync(sheet, 'utf-8')).map((c) => c.name)),
    );

    await expect(renderModule([...classes].sort())).toMatchFileSnapshot('./components-classes.ts');
  });
});
