import {
  Tree,
  formatFiles,
  joinPathFragments,
  logger,
  readProjectConfiguration,
  updateProjectConfiguration,
  visitNotIgnoredFiles,
} from '@nx/devkit';

export type DevtoolsAboutGeneratorSchema = {
  project: string;
  outputPath?: string;
  skipFormat?: boolean;
};

const SCRIPT_PATH = 'tools/generate-build-info.js';

const SCRIPT = `const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const [, , outputPath, packageJsonPath] = process.argv;

const read = (command) => {
  try {
    return execSync(command, { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return null;
  }
};

const version = fs.existsSync(packageJsonPath)
  ? JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8')).version
  : null;

const info = {
  version: version ?? 'unknown',
  sha: read('git rev-parse --short HEAD') ?? 'unknown',
  branch: read('git rev-parse --abbrev-ref HEAD') ?? 'unknown',
  builtAt: new Date().toISOString(),
};

const contents =
  '// Generated by ' +
  ${JSON.stringify(SCRIPT_PATH)} +
  ' - do not edit.\\n\\nexport const APP_BUILD_INFO = ' +
  JSON.stringify(info, null, 2) +
  ' as const;\\n';

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, contents);
`;

const PLACEHOLDER = `// Generated by ${SCRIPT_PATH} - do not edit.

export const APP_BUILD_INFO = {
  version: 'unknown',
  sha: 'unknown',
  branch: 'unknown',
  builtAt: '1970-01-01T00:00:00.000Z',
} as const;
`;

const relativeImport = (from: string, to: string) => {
  const fromParts = from.split('/').slice(0, -1);
  const toParts = to.replace(/\.ts$/, '').split('/');

  while (fromParts.length && toParts.length && fromParts[0] === toParts[0]) {
    fromParts.shift();
    toParts.shift();
  }

  const up = fromParts.length ? fromParts.map(() => '..') : ['.'];

  return [...up, ...toParts].join('/');
};

/** Wires the `provideQueryDevtools({ about })` call up to the generated constant, if it can be found. */
const wireProvider = (tree: Tree, projectRoot: string, outputPath: string) => {
  let wired = false;

  visitNotIgnoredFiles(tree, projectRoot, (file) => {
    if (wired || !file.endsWith('.ts')) return;

    const contents = tree.read(file, 'utf-8');

    if (!contents?.includes('provideQueryDevtools(')) return;

    if (!contents.includes('provideQueryDevtools()')) {
      logger.warn(
        `${file} already passes options to provideQueryDevtools() - add \`about: APP_BUILD_INFO\` to them yourself.`,
      );
      wired = true;

      return;
    }

    const importPath = relativeImport(file, outputPath);

    tree.write(
      file,
      `import { APP_BUILD_INFO } from '${importPath}';\n` +
        contents.replace('provideQueryDevtools()', 'provideQueryDevtools({ about: APP_BUILD_INFO })'),
    );
    wired = true;
  });

  return wired;
};

export const devtoolsAboutGenerator = async (tree: Tree, options: DevtoolsAboutGeneratorSchema) => {
  const project = readProjectConfiguration(tree, options.project);
  const outputPath = options.outputPath ?? joinPathFragments(project.sourceRoot ?? project.root, 'build-info.ts');

  if (!tree.exists(SCRIPT_PATH)) tree.write(SCRIPT_PATH, SCRIPT);
  if (!tree.exists(outputPath)) tree.write(outputPath, PLACEHOLDER);

  const gitignore = tree.read('.gitignore', 'utf-8') ?? '';

  // Regenerated on every build, and its SHA changes with every commit - committing it would put a
  // one-line diff in every commit that says nothing about the change.
  if (!gitignore.includes(outputPath)) tree.write('.gitignore', `${gitignore.trimEnd()}\n${outputPath}\n`);

  project.targets ??= {};
  project.targets['build-info'] = {
    executor: 'nx:run-commands',
    options: {
      commands: [`node ${SCRIPT_PATH} ${outputPath} ${joinPathFragments(project.root, 'package.json')}`],
    },
  };

  for (const target of ['build', 'serve']) {
    const config = project.targets[target];

    if (!config) continue;

    config.dependsOn ??= [];
    if (!config.dependsOn.includes('build-info')) config.dependsOn.push('build-info');
  }

  updateProjectConfiguration(tree, options.project, project);

  if (!wireProvider(tree, project.root, outputPath)) {
    logger.warn(
      `No provideQueryDevtools() call found in ${project.root} - pass \`about: APP_BUILD_INFO\` to it yourself.`,
    );
  }

  if (!options.skipFormat) await formatFiles(tree);
};

export default devtoolsAboutGenerator;
