import { TableComponent } from './components';
import {
  CellDefDirective,
  CellDirective,
  ColumnDefDirective,
  FooterCellDefDirective,
  FooterCellDirective,
  FooterRowComponent,
  FooterRowDefDirective,
  HeaderCellDefDirective,
  HeaderCellDirective,
  HeaderRowComponent,
  HeaderRowDefDirective,
  NoDataRowDirective,
  RecycleRowsDirective,
  RowComponent,
  RowDefDirective,
  TableBusyDirective,
  TextColumnComponent,
} from './partials';

export const TableImports = [
  TableComponent,
  RecycleRowsDirective,
  HeaderCellDefDirective,
  HeaderRowDefDirective,
  ColumnDefDirective,
  CellDefDirective,
  RowDefDirective,
  FooterCellDefDirective,
  FooterRowDefDirective,
  HeaderCellDirective,
  CellDirective,
  FooterCellDirective,
  HeaderRowComponent,
  RowComponent,
  FooterRowComponent,
  NoDataRowDirective,
  TextColumnComponent,
  TableBusyDirective,
] as const;
