#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn nx affected --target=lint --parallel --maxParallel 5 --cache && npx git-format-staged --formatter "prettier --stdin-filepath "{}""  "*.ts" "*.js" "*.tsx" "*.jsx" "*.json" "*.html" "*.md" "*.yml" "*.css" "*.scss"
