name: CI (Main)

on:
  push:
    branches:
      - main

concurrency: release_environment

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      pull-requests: write
      checks: write
    with:
      deploy: true
      storybook_target: storybook-prod
      docs_target: docs-prod
      channel_id: live
    secrets: inherit

  publish:
    needs: ci
    uses: ./.github/workflows/publish.yml
    with:
      version_command: 'yarn changeset:release'
      commit_message: 'chore: 🤖 update versions'
      title: 'Release packages'
      slack_title: '*New Release*'
    secrets: inherit
