name: CI (Next)

on:
  push:
    branches:
      - next

concurrency: next_environment

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      pull-requests: write
      checks: write
    with:
      deploy: true
      storybook_target: storybook-next
      docs_target: docs-next
      channel_id: live
    secrets: inherit

  publish:
    needs: ci
    uses: ./.github/workflows/publish.yml
    with:
      version_command: 'yarn changeset:prerelease'
      commit_message: 'chore: 🤖 update prereleases'
      title: 'Release prerelease packages'
      slack_title: '*New Next Release*'
    secrets: inherit
